### ISSUE TITLE
nonce

### ISSUE THREAD

**Issue by landabaso** [hayr-hotoca/react-native-chacha20-poly1305#1]
Could you please explain how is the nonce created? Can it be passed?

I understand that when using random nonces, there is some [risk of collision](https://en.wikipedia.org/wiki/ChaCha20-Poly1305#XChaCha20-Poly1305_%E2%80%93_extended_nonce_variant)?

**Comment by landabaso** [comment]
I went through the sources for iOS (I guess it's the same in Android?) and I believe that a [random nonce is being produced]( https://developer.apple.com/documentation/cryptokit/chachapoly/nonce/init()).

This may lead into issues. [See this discussion.](https://crypto.stackexchange.com/questions/77982/how-to-generate-a-nonce-for-chacha20-poly1305)

 Would you consider letting the user pass the nonce? There are some [interesting alternatives in the literature](https://crypto.stackexchange.com/a/10781/114037).

**Comment by hayr-hotoca** [comment]
For most users who are not cryptography experts, relying on proven cryptographic libraries like iOS's ChaChaPoly (https://developer.apple.com/documentation/cryptokit/chachapoly) and Android's Tink (https://developers.google.com/tink) is a safer approach. These libraries take care of the complex details, ensuring secure encryption and decryption.

For example, with the 1LimX app being offline, It's highly unlikely to experience a nonce collision, regardless of how much data a single user encrypts. A unique 256-bit encryption key and 2^96 possible nonces are more than sufficient for one person.

However, in situations where users require more functionality than the original library offers, creating a fork and making custom implementations is an option. For now, using the proven libraries provided by Apple and Google remains the safer choice.

I hope this is helpful!

**Comment by landabaso** [comment]
Thanks for your reply. In case you are interested, libsodium has an implementation of the extended version of chachapoly (xchacha20poly), that addresses this issue using 192-bit nonces and is considered to be safe to use with randomly-generated nonces. There is also a react-native implementation. It may be something interesting to explore and make your product even better. Thanks for providing this package and for your work.
